name: projet_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.6.1
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  http: ^1.2.2
  provider: ^6.1.2
  # Firebase Core : nécessaire pour initialiser Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  rxdart: ^0.27.6
  url_launcher: ^6.1.10
  intl: ^0.18.1
  # Cartes et géolocalisation
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  string_similarity: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
